/**
 * Resuelve el Taller número 4 del módulo 6 "Profundización Desarrollo de Software",
 * Programa CORFO "Mil Programadores".vv
 *
 * @autor Daniel Zúñiga Correa, 2017-12-13 (yyyy-mm-dd)
 */
package vista;

/**
 * Clase correspondiente a la vista principal
 *
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnConexionDB = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuSalir = new javax.swing.JMenu();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mnuOpcionesAgregar = new javax.swing.JMenuItem();
        mnuOpcionesEliminar = new javax.swing.JMenuItem();
        mnuOpcionesModificar = new javax.swing.JMenuItem();
        mnuOpcionesListar = new javax.swing.JMenuItem();
        mnuOpcionesManejar = new javax.swing.JMenuItem();
        mnuBD = new javax.swing.JMenu();
        mnuTipoConexion = new javax.swing.JMenu();
        mnuConexionOracleLocal = new javax.swing.JRadioButtonMenuItem();
        mnuConexionOracleNube = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuConexionMySqlLocal = new javax.swing.JRadioButtonMenuItem();
        mnuConexionMySqlNube = new javax.swing.JRadioButtonMenuItem();
        mnuCreacionTablas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VIDEO BUSTER");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("VIDEOBUSTER");

        mnuSalir.setText("Salir");

        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.setToolTipText("");
        mnuArchivoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuArchivoSalirMouseClicked(evt);
            }
        });
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuArchivoSalir);

        mnuPrincipal.add(mnuSalir);

        mnuOpciones.setText("Opciones");

        mnuOpcionesAgregar.setText("Agregar Películas");
        mnuOpciones.add(mnuOpcionesAgregar);

        mnuOpcionesEliminar.setText("Eliminar Películas");
        mnuOpciones.add(mnuOpcionesEliminar);

        mnuOpcionesModificar.setText("Modificar Películas");
        mnuOpciones.add(mnuOpcionesModificar);

        mnuOpcionesListar.setText("Listar Películas");
        mnuOpciones.add(mnuOpcionesListar);

        mnuOpcionesManejar.setText("Manejar Categorías");
        mnuOpciones.add(mnuOpcionesManejar);

        mnuPrincipal.add(mnuOpciones);

        mnuBD.setText("BD");
        mnuBD.setActionCommand("Base de Datos");

        mnuTipoConexion.setText("Tipo de Conexión");

        gbtnConexionDB.add(mnuConexionOracleLocal);
        mnuConexionOracleLocal.setText("DB Oracle Local");
        mnuConexionOracleLocal.setToolTipText("");
        mnuTipoConexion.add(mnuConexionOracleLocal);

        gbtnConexionDB.add(mnuConexionOracleNube);
        mnuConexionOracleNube.setText("DB Oracle Nube");
        mnuTipoConexion.add(mnuConexionOracleNube);
        mnuTipoConexion.add(jSeparator1);

        gbtnConexionDB.add(mnuConexionMySqlLocal);
        mnuConexionMySqlLocal.setSelected(true);
        mnuConexionMySqlLocal.setText("DB MySql Local");
        mnuTipoConexion.add(mnuConexionMySqlLocal);

        gbtnConexionDB.add(mnuConexionMySqlNube);
        mnuConexionMySqlNube.setText("DB MySql Nube");
        mnuTipoConexion.add(mnuConexionMySqlNube);

        mnuBD.add(mnuTipoConexion);

        mnuCreacionTablas.setText("Creación de Tablas");
        mnuBD.add(mnuCreacionTablas);

        mnuPrincipal.add(mnuBD);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed

    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    private void mnuArchivoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuArchivoSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup gbtnConexionDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JMenuItem mnuArchivoSalir;
    public javax.swing.JMenu mnuBD;
    public javax.swing.JRadioButtonMenuItem mnuConexionMySqlLocal;
    public javax.swing.JRadioButtonMenuItem mnuConexionMySqlNube;
    public javax.swing.JRadioButtonMenuItem mnuConexionOracleLocal;
    public javax.swing.JRadioButtonMenuItem mnuConexionOracleNube;
    public javax.swing.JMenuItem mnuCreacionTablas;
    public javax.swing.JMenu mnuOpciones;
    public javax.swing.JMenuItem mnuOpcionesAgregar;
    public javax.swing.JMenuItem mnuOpcionesEliminar;
    public javax.swing.JMenuItem mnuOpcionesListar;
    public javax.swing.JMenuItem mnuOpcionesManejar;
    public javax.swing.JMenuItem mnuOpcionesModificar;
    public javax.swing.JMenuBar mnuPrincipal;
    public javax.swing.JMenu mnuSalir;
    public javax.swing.JMenu mnuTipoConexion;
    // End of variables declaration//GEN-END:variables
}
